site_name: Scan Selos Bidimensional

nav:
  - Apresentação:
    - Apresentação: index.md
    
  - Arquitetura:
    - Arquitetura ScanSelos: arquitetura/arquitetura.md

  - Manual Operação: 
    - Aplicação Desktop: manual/instalacao.md
    - Ambiente Web: manual/ambiente_web.md
  
  - Integrações: 
    - Consumo de selos: integracao/integracao_bilhetagem.md
    - Fluxo após consumo se selos: integracao/pos_consumo_selos.md


theme: 
  name: readthedocs

